# Generated by Django 3.0.5 on 2020-04-10 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Distance',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('formatted_origin', models.CharField(max_length=250)),
                ('origin_lat', models.DecimalField(decimal_places=20, max_digits=30, null=True)),
                ('origin_long', models.DecimalField(decimal_places=20, max_digits=30, null=True)),
                ('formatted_destination', models.CharField(max_length=250)),
                ('destination_lat', models.DecimalField(decimal_places=20, max_digits=30, null=True)),
                ('destination_long', models.DecimalField(decimal_places=20, max_digits=30, null=True)),
                ('calculated_distance', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('location_id', models.AutoField(primary_key=True, serialize=False)),
                ('location', models.CharField(max_length=250, null=True)),
                ('location_lat', models.DecimalField(decimal_places=20, max_digits=30, null=True)),
                ('location_long', models.DecimalField(decimal_places=20, max_digits=30, null=True)),
                ('formatted_location', models.CharField(max_length=250, null=True)),
            ],
        ),
    ]
